# Generated by Django 4.2.7 on 2023-11-09 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedShot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("blocker", models.CharField(max_length=255)),
                ("shooter", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("team", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Faceoff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("winner", models.CharField(max_length=255)),
                ("loser", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Giveaway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("player", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("shot_type", models.CharField(max_length=255)),
                ("strength", models.CharField(max_length=255)),
                ("empty_net", models.BooleanField()),
                ("game_winning_goal", models.BooleanField()),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("scorer", models.CharField(max_length=255)),
                ("assist", models.CharField(max_length=255)),
                ("assist2", models.CharField(max_length=255)),
                ("goalie", models.CharField(max_length=255)),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("hitter", models.CharField(max_length=255)),
                ("hittee", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MissedShot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("shooter", models.CharField(max_length=255)),
                ("goalie", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("penalty_on", models.CharField(max_length=255)),
                ("drew_by", models.CharField(max_length=255)),
                ("penalty_type", models.CharField(max_length=255)),
                ("minutes", models.IntegerField()),
                ("severity", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Shot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("shooter", models.CharField(max_length=255)),
                ("goalie", models.CharField(max_length=255)),
                ("shot_type", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("goalie", models.CharField(max_length=255)),
                ("shooter", models.CharField(max_length=255)),
                ("shot_type", models.CharField(max_length=255)),
                ("period", models.IntegerField()),
                ("period_time", models.TimeField()),
                ("season_type", models.CharField(max_length=255)),
                ("coord_x", models.IntegerField()),
                ("coord_y", models.IntegerField()),
                ("game_id", models.IntegerField()),
            ],
        ),
    ]
