# Generated by Django 4.2.7 on 2023-11-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Challenge",
        ),
        migrations.DeleteModel(
            name="Stop",
        ),
        migrations.RenameField(
            model_name="missedshot",
            old_name="description",
            new_name="reason",
        ),
        migrations.RemoveField(
            model_name="blockedshot",
            name="description",
        ),
        migrations.RemoveField(
            model_name="faceoff",
            name="description",
        ),
        migrations.RemoveField(
            model_name="giveaway",
            name="description",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="description",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="empty_net",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="game_winning_goal",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="strength",
        ),
        migrations.RemoveField(
            model_name="hit",
            name="description",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="description",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="severity",
        ),
        migrations.RemoveField(
            model_name="shot",
            name="description",
        ),
    ]
