# Generated by Django 4.2.7 on 2023-11-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_delete_challenge_delete_stop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedshot",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="blockedshot",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="drew_by",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="coord_x",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="coord_y",
            field=models.IntegerField(null=True),
        ),
    ]
