# Generated by Django 4.2.7 on 2023-11-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_blockedshot_coord_x_alter_blockedshot_coord_y_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedshot",
            name="blocker",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="blockedshot",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="blockedshot",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="blockedshot",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="blockedshot",
            name="shooter",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="loser",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="winner",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="player",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="assist",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="assist2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goalie",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="scorer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="shot_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="hittee",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="hitter",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="goalie",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="reason",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="shooter",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="minutes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="penalty_on",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="penalty_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="goalie",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="period",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="period_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="season_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="shooter",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="shot_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
