# Generated by Django 4.2.7 on 2023-11-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_blockedshot_blocker_alter_blockedshot_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedshot",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="faceoff",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="giveaway",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="hit",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="missedshot",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="penalty",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name="shot",
            name="event_id",
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
