# Generated by Django 4.2.7 on 2023-11-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_blockedshot_event_id_faceoff_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedshot",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="faceoff",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="giveaway",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="missedshot",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name="shot",
            name="event_id",
            field=models.CharField(default=-1, unique=True),
        ),
    ]
