# Generated by Django 4.2.7 on 2026-05-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_blockedshot_event_id_alter_faceoff_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedshot',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='faceoff',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='missedshot',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='event_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
