# Generated by Django 4.2.7 on 2026-05-03 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0003_initial'),
        ('players', '0004_initial'),
        ('events', '0008_drop_legacy_event_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nhl_event_id', models.CharField(max_length=64, unique=True)),
                ('type_desc', models.CharField(choices=[('goal', 'Goal'), ('shot-on-goal', 'Shot on Goal'), ('hit', 'Hit'), ('faceoff', 'Faceoff'), ('giveaway', 'Giveaway'), ('takeaway', 'Takeaway'), ('penalty', 'Penalty'), ('blocked-shot', 'Blocked Shot'), ('missed-shot', 'Missed Shot')], db_index=True, max_length=32)),
                ('type_code', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('period_time', models.TimeField(blank=True, null=True)),
                ('period_type', models.CharField(blank=True, max_length=8, null=True)),
                ('coord_x', models.IntegerField(blank=True, null=True)),
                ('coord_y', models.IntegerField(blank=True, null=True)),
                ('zone_code', models.CharField(blank=True, max_length=1, null=True)),
                ('situation_code', models.CharField(blank=True, max_length=4, null=True)),
                ('shot_type', models.CharField(blank=True, max_length=32, null=True)),
                ('penalty_type', models.CharField(blank=True, max_length=64, null=True)),
                ('penalty_minutes', models.IntegerField(blank=True, null=True)),
                ('miss_reason', models.CharField(blank=True, max_length=64, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='games.game')),
                ('goalie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goalie_events', to='players.player')),
                ('primary_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_events', to='players.player')),
                ('secondary_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_events', to='players.player')),
                ('tertiary_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertiary_events', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['type_desc', 'primary_player'], name='events_even_type_de_c9b1d9_idx'), models.Index(fields=['type_desc', 'secondary_player'], name='events_even_type_de_8fe89d_idx'), models.Index(fields=['type_desc', 'goalie'], name='events_even_type_de_c53284_idx'), models.Index(fields=['game', 'period', 'period_time'], name='events_even_game_id_f913bc_idx')],
            },
        ),
    ]
