# Generated by Django 4.2.7 on 2023-11-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("season", models.CharField(max_length=8)),
                ("game_date", models.DateField()),
                ("game_start", models.TimeField()),
                ("game_end", models.TimeField()),
                ("winner", models.CharField(max_length=3)),
                ("loser", models.CharField(max_length=3)),
                ("home_team", models.CharField(max_length=3)),
                ("away_team", models.CharField(max_length=3)),
                ("home_goals", models.IntegerField()),
                ("away_goals", models.IntegerField()),
                ("gameId", models.IntegerField()),
            ],
        ),
    ]
