# Generated by Django 4.2.7 on 2026-05-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_drop_legacy_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(db_index=True)),
                ('game_type', models.SmallIntegerField(choices=[(1, 'Preseason'), (2, 'Regular Season'), (3, 'Playoff'), (4, 'All-Star / Other')])),
                ('game_date', models.DateField(db_index=True)),
                ('start_time_utc', models.DateTimeField(blank=True, null=True)),
                ('home_team', models.CharField(max_length=3)),
                ('away_team', models.CharField(max_length=3)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=128, null=True)),
                ('game_state', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'game_type'], name='games_game_season_17475b_idx'), models.Index(fields=['home_team'], name='games_game_home_te_229547_idx'), models.Index(fields=['away_team'], name='games_game_away_te_b462f5_idx')],
            },
        ),
    ]
