# Generated by Django 4.2.7 on 2026-05-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_drop_legacy_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('nhl_api_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('full_name', models.CharField(db_index=True, max_length=256)),
                ('player_slug', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sweater_number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('C', 'Center'), ('L', 'Left Wing'), ('R', 'Right Wing'), ('D', 'Defense'), ('G', 'Goalie')], max_length=2)),
                ('shoots_catches', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], max_length=1, null=True)),
                ('headshot_url', models.URLField(blank=True, max_length=512, null=True)),
                ('hero_image_url', models.URLField(blank=True, max_length=512, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_state_province', models.CharField(blank=True, max_length=128, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=3, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.IntegerField(blank=True, null=True)),
                ('in_hhof', models.BooleanField(default=False)),
                ('in_top_100', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='players_pla_last_na_1786cf_idx'), models.Index(fields=['player_slug'], name='players_pla_player__e4a31f_idx'), models.Index(fields=['position'], name='players_pla_positio_2502c1_idx')],
            },
        ),
    ]
